collections:
  members:
    output: true
    years:
      - Honorary
      - 2014
      - 2015
      - 2016
      - 2017
      - 2018
      - 2019
      - 2020
      - 2021

current_year: 2021

title: Bell Senior Society
description: "Technology & Entrepreneurship Senior Society at the University of Pennsylvania"
author:
  name: Bell Senior Society
  email: bell.senior.society@gmail.com
  github: bellsociety

production_url: http://www.bellsociety.com
exclude:
  - bin

markdown: kramdown
encoding: UTF-8

gems:
  - jekyll-redirect-from
